apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-test-dep
  name: spring-test-dep
  namespace: la
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: spring-test-dep
  template:
    metadata:
      labels:
        app: spring-test-dep
    spec:
      containers:
        - image: gcr.io/p8-integrations-eu-dev-2/spring-test:latest
          imagePullPolicy: Always
          name: spring-boot-container
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 30
