apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-test-dep
  name: spring-test-svc
  namespace: la
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-test-dep
  sessionAffinity: None
  type: NodePort
